name: build hluda-server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison xz-utils ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configurar NDK de Android
        uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r25c

      - name: Clonar Frida 16.7.14
        run: |
          git clone --recurse-submodules --branch 16.7.14 https://github.com/frida/frida

      - name: Inyectar Parches y Compilar Frida (arm64)
        run: |
          
          git config --global user.email "davidmonge975@gmail.com"
          git config --global user.name "mrfear"
          
          # 1. INYECCIÓN MANUAL DEL UUID (Bypass del parche 0002)
          python3 -c "
          file_path = 'frida/subprojects/frida-core/server/server.vala'
          with open(file_path, 'r') as f:
              code = f.read()
          
          
          code = code.replace('private const string DEFAULT_DIRECTORY = \"re.frida.server\";', 'private static string DEFAULT_DIRECTORY = null;')
          
          
          old_main = 'private static int main (string[] args) {'
          new_main = 'private static int main (string[] args) {\n\t\tDEFAULT_DIRECTORY = GLib.Uuid.string_random();'
          code = code.replace(old_main, new_main)
          
          with open(file_path, 'w') as f:
              f.write(code)
          print('Patch from UUID inyected successfuly in server.vala')
          "

          # 2. 
          if [ -d "Patchs/strongR-frida/frida-core" ]; then
            echo "Aplicando el resto de parches de ocultamiento..."
            cd frida/subprojects/frida-core
            for patch in ../../../Patchs/strongR-frida/frida-core/*.patch; do
              echo "Aplicando: \$(basename \"\$patch\")"
              git am --keep-cr "\$patch" || exit 1
            done
            cd ../../..
          else
            echo "WARNING: Patchs not found in it's folder."
          fi

          # 3. ARM64
          cd frida
          make server-android-arm64
          make inject-android-arm64
          make gadget-android-arm64

      - name: Empaquetar Binarios
        run: |
          mkdir -p releases_output
          
          # Compress and move
          cd frida/build/frida-android-arm64/bin
          gzip -9 frida-server
          gzip -9 frida-inject
          mv frida-server.gz ../../../../../releases_output/
          mv frida-inject.gz ../../../../../releases_output/
          
          cd ../lib/frida
          gzip -9 frida-gadget.so
          mv frida-gadget.so.gz ../../../../../releases_output/

      - name: Publicar en Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 16.7.14-hluda
          name: hluda-server 16.7.14 (arm64)
          files: releases_output/*
          fail_on_unmatched_files: true
